In [18]:
from sklearn import tree
from sklearn.model_selection import train_test_split
import numpy as np
import pandas as pd

In [19]:
data=pd.read_csv('Z:\ML lab\PlayTennis.csv')

In [20]:
data

    Day   Outlook Temperature Humidity    Wind Play Tennis
0    D1     Sunny         Hot     High    Weak          No
1    D2     Sunny         Hot     High  Strong          No
2    D3  Overcast         Hot     High    Weak         Yes
3    D4      Rain        Mild     High    Weak         Yes
4    D5      Rain        Cool   Normal    Weak         Yes
5    D6      Rain        Cool   Normal  Strong          No
6    D7  Overcast        Cool   Normal  Strong         Yes
7    D8     Sunny        Mild     High    Weak          No
8    D9     Sunny        Cool   Normal    Weak         Yes
9   D10      Rain        Mild   Normal    Weak         Yes
10  D11     Sunny        Mild   Normal  Strong         Yes
11  D12  Overcast        Mild     High  Strong         Yes
12  D13  Overcast         Hot   Normal    Weak         Yes
13  D14      Rain        Mild     High  Strong          No

In [21]:
from sklearn.preprocessing import LabelEncoder

In [22]:
Le=LabelEncoder()

In [23]:
data['Outlook']=Le.fit_transform(data['Outlook'])
data['Temperature']=Le.fit_transform(data['Temperature'])
data['Humidity']=Le.fit_transform(data['Humidity'])
data['Wind']=Le.fit_transform(data['Wind'])
data['PlayTennis']=Le.fit_transform(data['Play Tennis'])

In [24]:
data

    Day  Outlook  Temperature  Humidity  Wind Play Tennis  PlayTennis
0    D1        2            1         0     1          No           0
1    D2        2            1         0     0          No           0
2    D3        0            1         0     1         Yes           1
3    D4        1            2         0     1         Yes           1
4    D5        1            0         1     1         Yes           1
5    D6        1            0         1     0          No           0
6    D7        0            0         1     0         Yes           1
7    D8        2            2         0     1          No           0
8    D9        2            0         1     1         Yes           1
9   D10        1            2         1     1         Yes           1
10  D11        2            2         1     0         Yes           1
11  D12        0            2         0     0         Yes           1
12  D13        0            1         1     1         Yes           1
13  D14        1            2         0     0          No           0

In [25]:
x=data.iloc[:,1:-1]
y=data['Play Tennis']

In [26]:
print(x,y)

    Outlook  Temperature  Humidity  Wind Play Tennis
0         2            1         0     1          No
1         2            1         0     0          No
2         0            1         0     1         Yes
3         1            2         0     1         Yes
4         1            0         1     1         Yes
5         1            0         1     0          No
6         0            0         1     0         Yes
7         2            2         0     1          No
8         2            0         1     1         Yes
9         1            2         1     1         Yes
10        2            2         1     0         Yes
11        0            2         0     0         Yes
12        0            1         1     1         Yes
13        1            2         0     0          No 0      No
1      No
2     Yes
3     Yes
4     Yes
5      No
6     Yes
7      No
8     Yes
9     Yes
10    Yes
11    Yes
12    Yes
13     No
Name: Play Tennis, dtype: object

In [28]:
model=tree.DecisionTree.Classifier(criteria='entropy')
model.fit(x,y)

AttributeError: module 'sklearn.tree' has no attribute 'DecisionTree'